
import { Category, Product, DailyEntry } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'MERCADERIA' },
  { id: '2', name: 'PULPA' },
  { id: '3', name: 'DESCARTABLE' },
  { id: '4', name: 'PANES' },
  { id: '5', name: 'CARNES' },
  { id: '6', name: 'EMPANADAS' },
  { id: '7', name: 'LIMPIEZA' },
  { id: '8', name: 'FIAMBRES' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // MERCADERIA (Updated)
  { id: 'm1', name: 'Maizena', categoryId: '1' },
  { id: 'm2', name: 'Azucar', categoryId: '1' },
  { id: 'm3', name: 'Arroz', categoryId: '1' },
  { id: 'm4', name: 'Semola', categoryId: '1' },
  { id: 'm5', name: 'Lenteja', categoryId: '1' },
  { id: 'm6', name: 'Fideo', categoryId: '1' },
  { id: 'm7', name: 'Harinas', categoryId: '1' },
  { id: 'm8', name: 'Triturado', categoryId: '1' },
  { id: 'm9', name: 'Aceitunas VERDES', categoryId: '1' },
  { id: 'm10', name: 'Sal Gruesa', categoryId: '1' },
  { id: 'm11', name: 'Atun', categoryId: '1' },
  { id: 'm12', name: 'Arveja', categoryId: '1' },
  { id: 'm13', name: 'Choclo', categoryId: '1' },
  { id: 'm14', name: 'Sal', categoryId: '1' },
  { id: 'm15', name: 'Aceitunas Negras', categoryId: '1' },
  { id: 'm16', name: 'Jugos de naranja', categoryId: '1' },
  { id: 'm17', name: 'ACEITE X 5 L', categoryId: '1' },
  { id: 'm18', name: 'Mayonesa 3kg', categoryId: '1' },
  { id: 'm19', name: 'Savora porc', categoryId: '1' },
  { id: 'm20', name: 'Mayonesa porc', categoryId: '1' },
  { id: 'm21', name: 'Ketchup porc', categoryId: '1' },
  { id: 'm22', name: 'Savora 3kg', categoryId: '1' },
  { id: 'm23', name: 'Durazno en lata', categoryId: '1' },
  { id: 'm24', name: 'Mermeladas', categoryId: '1' },
  { id: 'm25', name: 'Pulpa frutillas', categoryId: '1' },
  { id: 'm26', name: 'Pulpa Anana', categoryId: '1' },
  { id: 'm27', name: 'Pulpa Durazno', categoryId: '1' },
  { id: 'm28', name: 'Pulpa Maracuya', categoryId: '1' },
  { id: 'm29', name: 'Pulpa Arandanos', categoryId: '1' },
  { id: 'm30', name: 'Maple de huevo', categoryId: '1' },

  { id: 'p2', name: 'Pulpa de Frutilla', categoryId: '2' },
  { id: 'p3', name: 'Bolsas Camiseta', categoryId: '3' },
  { id: 'd1', name: 'Escarbadientes', categoryId: '3' },
  { id: 'd2', name: 'Papel film', categoryId: '3' },
  { id: 'd3', name: 'Laminas folex', categoryId: '3' },
  { id: 'd4', name: 'Papel gris', categoryId: '3' },
  { id: 'd5', name: 'Pote ensalada 1/2', categoryId: '3' },
  { id: 'd6', name: 'Pote postre 1/4', categoryId: '3' },
  { id: 'd7', name: 'Pote licuado', categoryId: '3' },
  { id: 'd8', name: 'Vasos descartables mangas', categoryId: '3' },
  { id: 'd9', name: 'Servilletas 33x33', categoryId: '3' },
  { id: 'd10', name: 'Servilletas 18x18', categoryId: '3' },
  { id: 'd11', name: 'Vasos termicos mangas', categoryId: '3' },
  { id: 'd12', name: 'Bolsas de papel n4', categoryId: '3' },
  { id: 'd13', name: 'Bandeja 103', categoryId: '3' },
  { id: 'd14', name: 'Bandeja 102', categoryId: '3' },
  { id: 'd15', name: 'Bandeja 105', categoryId: '3' },
  { id: 'd16', name: 'Guantes descartables', categoryId: '3' },
  { id: 'd17', name: 'Tenedor', categoryId: '3' },
  { id: 'd18', name: 'Cuchillos', categoryId: '3' },
  { id: 'd19', name: 'Cucharas', categoryId: '3' },
  { id: 'd20', name: 'Cucharitas', categoryId: '3' },
  { id: 'd21', name: 'Bandeja de carton N2', categoryId: '3' },
  { id: 'd22', name: 'BOLSA CORTE 70X50', categoryId: '3' },
  { id: 'd23', name: 'BOLSA CORTE 15X25', categoryId: '3' },
  { id: 'd24', name: 'Caja pizza', categoryId: '3' },
  { id: 'p4', name: 'Pan Francés', categoryId: '4' },
  { id: 'p5', name: 'Asado de Tira', categoryId: '5' },
  { id: 'p6', name: 'Vacío', categoryId: '5' },
  { id: 'p7', name: 'Jamón Cocido', categoryId: '6' },
  { id: 'p8', name: 'Queso Tybo', categoryId: '6' },
  { id: 'l1', name: 'Lavandina', categoryId: '7' },
  { id: 'l2', name: 'Detergente', categoryId: '7' },
  { id: 'l3', name: 'Desodorante piso', categoryId: '7' },
  { id: 'l4', name: 'Desengrasante', categoryId: '7' },
  { id: 'l5', name: 'Alcohol', categoryId: '7' },
  { id: 'l6', name: 'Jabon liqudo', categoryId: '7' },
  { id: 'l7', name: 'Cif', categoryId: '7' },
  { id: 'l8', name: 'Esponja', categoryId: '7' },
  { id: 'l9', name: 'Esponja alambre', categoryId: '7' },
  { id: 'l10', name: 'Rejilla', categoryId: '7' },
  { id: 'l11', name: 'Trapo de piso', categoryId: '7' },
  { id: 'l12', name: 'Paños Absorbentes', categoryId: '7' },
  { id: 'l13', name: 'Blem', categoryId: '7' },
  { id: 'l14', name: 'Amoniaco para baño', categoryId: '7' },
  { id: 'l15', name: 'Guantes', categoryId: '7' },
  { id: 'l16', name: 'Mata mosquito', categoryId: '7' },
  { id: 'l17', name: 'Nastalina', categoryId: '7' },
  { id: 'l18', name: 'Mata cucaracha', categoryId: '7' },
  { id: 'l19', name: 'Poett', categoryId: '7' },
  { id: 'l20', name: 'Bolsa de consorcio', categoryId: '7' },
];

export const INITIAL_ENTRIES: DailyEntry[] = [];

// Actualizamos a v5 para limpiar cualquier dato de prueba anterior en el navegador del usuario
export const STORAGE_KEY = 'market_kathe_data_v6';

export const SALES_CATEGORIES = ['PANES', 'CARNES', 'EMPANADAS', 'MERCADERIA'];
